### ISSUE TITLE
status string becomes undefined inside Model.find() query, when immediately after creating an object for the Model which has state machine

### ISSUE THREAD

**Issue by Narayanan2696** [safer-bwd/mongoose-state-machine#4]
```
const findOrderByStatus = (orderDetails) => {
  console.log('order details:', orderDetails); // printing orderStatus value which is 'requested'
  return Order.find({ orderDetails }); // but here orderDetails containing status becomes undefined value becomes undefined
};
```

**output:**
console.log: prints **{ orderStatus: 'requested', orderedBy: 5ed679dff46f02232fd5988a }**
but while passed to Order.find the orderStatus changes to undefined like below:
Mongoose: **Order.find({ orderStatus: undefined, orderedBy: ObjectId("5ed679dff46f02232fd5988a") }, { projection: {} })**

**State machine declaration**
```
orderStatus: {
      type: Types.String,
      required: true,
    },

const stateMachine = { // state machines transitions and methods};

orderSchema.plugin(stateMachinePlugin, {
  fieldName: 'orderStatus',
  stateMachine,
});
```

This issue is occurring only when a new object is created for the model where the state machine is defined, once the server is restarted it is working properly it is able to pick 'registered', again when a new object is created again it becomes undefined, each and every time if the server is restarted after creating a new object, then only the find query is able to take the passed **orderStatus** string.

To confirm this is an issue with safer-bwd state machine, I tried querying with an attribute which is of non state machine, it is able to get the value passed to the query it is not undefined. 

I appreciate if this issue is addressed immediately and help me out with proceeding with safer-bwd state machine.

Thanks.

**Comment by safer-bwd** [comment]
Thanks for the detailed description of the problem.
I added a test that repeats the bug and fixed it.
